### ISSUE TITLE
Updates/Releases

### ISSUE THREAD

**Issue by davewatson91** [lmagyar/homeassistant-addon-tailscale#60] opened 2023-09-09 22:49 UTC
Hey mate, 

Appreciate the work with this - unfortunately the last update you did caused quite a few dramas for my entire network (I had my DNS running through my HA node). 

Any chance when you do a release, you could add just a couple of notes in what you've changed? It ended up being the proxy option, but it took a lot of work through proccess of elimination to work out what kept crashing the add-on. 

Defaulting some of these options to 'true', might not be the best option as far as introducing 'breaking' changes (happy to accept that these may not be breaking changes for everyone, but any change in configuration could potentially introduce them). 

Just a couple of thoughts, and I definitely appreciate the effort you've put into maintaining a more up to date fork!

**Comment by lmagyar** [comment] 2023-09-09 23:45
Gosh, now I understand the unintended consequences. :( Sorry for this mess.

It was in the changelog (_0.11.1.21 (forked) - Properly test Home Assistant's HTTP reverse proxy configuration (especially test use_x_forwarded_for settings)_), it was a test for proper HA reverse proxy configuration, and the error was in the log, mentioning the documentation of the proxy settings.

It was intended as a harmless fix for a test. A test that helps new users.

But...

The default HA config will cause the test to fail, and the add-on will not start. This is "OK" for new users. But people who has never used the proxy function didn't noticed that it returned HTTP 400 previously, and I followed the concept of the original add-on to fail if something is non-functional.

And the original concept is that everything is enabled by default. If I disable proxy (and funnel) by default now, the most used functions will disappear for all users. That would be more painful.

The only thing I can think I can do now is to add a notice to the change-log.

I'm sorry for this mess. I was in a hurry, and now I have to start to the airport within an hour. I can't think a better quick fix for now. :(

**Comment by davewatson91** [comment] 2023-09-10 00:20
Super quick reply! Seriously, it's not a worry at all - totally understand these things happen. As much as anything else, I wanted to raise it so that if someone else was having issues, they could see an issue/resolution 👍🏼 

Totally understand how you were looking at this - definitely had never checked the add-on logs at all before I had an issue, so that's on me too! 🥲

I didn't actually notice the changelog was in the files there sorry! I had checked the release notes (which is what shows up in HA as well) - might just be worth adding it into there as well? 😄

**Comment by lmagyar** [comment] 2023-09-17 14:49
So, I'm back, the notice/warning is part of the "release notes", that comes from the changelog. I hope other users saw this notice/warning in time. Closing this issue for now.

**Closed by lmagyar** 2023-09-17 14:49 UTC
