### ISSUE TITLE
HA unreachable!

### ISSUE THREAD

**Issue by Loweack** [lmagyar/homeassistant-addon-tailscale#20] opened 2023-05-09 16:11 UTC
Be careful with the latest update, HA become unreachable either with the URL of my reverse proxy or even directly via the IP address!!
Only solution: plug the RPi4 to a display and disable manually the addon (by doing: addons stop "*slug name*").
To get the "slug name", you need to type "ha addons list".

**Comment by lmagyar** [comment] 2023-05-09 18:00
What is your network configuration? What URL is unreachable? What is your reverse proxy (Tailscale's builtin proxy, or another eg. NGINX proxy)?

There are 2 significant changes in this version, merged from the official add-on:
- Removed: --tun=userspace-networking (from now on there is a real `tailscale0` interface on the host)
- Added: --accept-dns

**Comment by Loweack** [comment] 2023-05-09 19:25
What is your network configuration? >> A classic one I would say, nothing special.
What URL is unreachable? >> The public one through my FQDN and the local one with the IP 192.168.X.X:8123 (none of them could be pinged)
What is your reverse proxy? >> I host via Docker a NGINX (NGINX Proxy Manager).

As soon as I disabled the addon, my HA came back to life.

**Comment by lmagyar** [comment] 2023-05-09 21:10
Hmmm, quite similar to mine (DuckDNS, NGINX, HA, Tailscale, eth0, NAT).

As I understand, your host lost it network access completely.

Strange. Now I'm just guessing. Seems that the presence of Tailscale's `tailscale0` interface screwed your routing. Maybe something else has 100.x.x.x IP in your config. Maybe some routing is added manually. Maybe some Tailscale subnet routing is enabled/configured to another Tailscale client's 192.168.x.x subnet. It seems to me, that all 192.168.x.x traffic of your host was redirected to somewhere else, other than the real router, maybe sent to the add-on's `tailscale0` interface, or anywhere. But I'm just guessing.

If you have access to the host (not the SSH add-on, but to the host OS), you can access the logs of the stopped add-on with `journalctl CONTAINER_NAME=addon_09716aab_tailscale > /mnt/data/supervisor/share/tailscale.log` And you can access the log as a text file at `/share/tailscale.log` Search for the word "route". Maybe there will be some strange thing going on. My guess is, when tailscaled started it broke your host's routing. But why? How?

**Comment by lmagyar** [comment] 2023-05-09 21:19
I'm just thinking to make this non-userspace-networking mode optional, make the previous userspace-networking the default, and add a config option to turn it off (like taildrop, proxy, funnel, etc. all have this optionality). So anybody in the future have to manually disable userspace-networking to use `tailscale0` as a real interface.

And make a PR to the official add-on...

**Comment by Loweack** [comment] 2023-05-10 06:24
> Maybe some routing is added manually. Maybe some Tailscale subnet routing is enabled/configured to another Tailscale client's 192.168.x.x subnet.
The only thing I had, is that Tailscale through HA could act as an exit node (but it wasn't enable on the admin panel of Tailscale)

> If you have access to the host (not the SSH add-on, but to the host OS), you can access the logs of the stopped add-on with journalctl CONTAINER_NAME=addon_09716aab_tailscale > /mnt/data/supervisor/share/tailscale.log And you can access the log as a text file at /share/tailscale.log Search for the word "route". Maybe there will be some strange thing going on. My guess is, when tailscaled started it broke your host's routing. But why? How?
I'll try to give you some logs, but as I uninstalled your fork to come back to the "official" addon, I don't know if the logs are still there. But I'll try anyway!

**Comment by lmagyar** [comment] 2023-05-10 07:58
If exit node is not enabled, that shouldn't be a problem.

With journalctl from the OS command line you can access uninstalled add-on's logs.

Be aware with the next version of the official add-on, it will contain the exact same changes. I will make a PR soon, check whether sg. like "Make userspace networking configurable" PR is in the changelog of the next release of the official add-on, if not, do not update until it is.

**Comment by lmagyar** [comment] 2023-05-10 09:26
New v0.11.1.3 version is out, this is by default uses userspace networking again (like all previous versions before), so if you install/update to it from your console, it should not break your networking on the host. You need to add `userspace_networking: false` to get back the broken v0.11.1.2 functionality. If you can test it, this would be a proof of the "danger" of non-userspace-networking.

If it still doesn't help, I run out of ideas. :( The only other thing that is changed in the broken v0.11.1.2 is adding `--accept-dns`, but that should not break IP level networking, though you can disable even this with adding `accept_dns: false` to the configuration.

**Comment by lmagyar** [comment] 2023-05-10 09:46
FYI The PR is https://github.com/hassio-addons/addon-tailscale/pull/199

**Comment by elcajon** [comment] 2023-05-10 12:25
A question about this because I also had a problem with routing in the past when I started experimenting with userspace. 
The interface (type tun) is not managed via the network manager If a subnet router with the local IP addresses is set up, however, the system tries to send the local data via the tailscale interface, which theoretically works but not in connection with the network manager in HA OS.
Have you tested if the configuration works when the subnet router is deactivated via the Tailscale Admin interface?

**Comment by lmagyar** [comment] 2023-05-10 13:48
Hmmm, so when a subnet routing is active with the local IP domain, we should not allow non-userspace-networking? Seems plausible.

Frenck also knows about this "losing network access altogether" problem, that is the reason it is not released in the official add-on, but I have no more information about his plans on the solution.

**Comment by lmagyar** [comment] 2023-05-10 15:07
With `/opt/tailscale status --self=false --peers=true --json | jq -rc '.Peer[] | select(has("PrimaryRoutes")) | .PrimaryRoutes[]' | sort -u` we can list all the subnet routes in the Tailnet.

We can then force using userspace networking to avoid this routing problem when the allowed external subnets (above) has any overlap with the local advertised subnet routes.

But what happens when the add-on is already using tun (not userspace-networking), and on the Admin interface somebody allows the local IP domain to be routed somewhere else? I don't know the internals of the network manager, and whether Tailscaled will try to modify the host routing and break everything on the fly?

**Comment by elcajon** [comment] 2023-05-10 15:29
We could create a s6 service that periodically checks if local subnet routes are available in the tailnet and then restarts the service (with/without userspace) but that would also be more of a workaround. 
The real question would be if there is the possibility upstream in HA-OS and/or HA-Supervisor to get the tunnel interfaces working within the HA environment.

**Comment by lmagyar** [comment] 2023-05-10 16:20
I've read these https://github.com/tailscale/tailscale/issues/1227 https://github.com/tailscale/tailscale/issues/6231 https://github.com/tailscale/tailscale/issues/5999 https://github.com/tailscale/tailscale/issues/1344

Summary:
- This is a 2 year old issue.
- Tailscale uses table 52 for route settings and it has higher priority than the main route table.
- Reason: if a coffe shop has the same IP as eg. your home network, you will still access your home network subnet from the coffee shop.

Solution:
- HA devices won't go to coffee shops, so we should use the solution from https://github.com/tailscale/tailscale/issues/6231#issuecomment-1418124609
- ie: `ip rule add to <local subnets> priority 5000 table main`

We can add/remove these rules when tailscale start/stop, from now on tailscale won't break local routing?

What do you think? It wouldn't take too much for me to implement it, the big question, who will test it and rist to brick it's config? :D

**Comment by elcajon** [comment] 2023-05-10 17:50
Might be worth a try, I don't have a test instance running right now, I might manage to set up a VM in proxmox this weekend.

**Comment by lmagyar** [comment] 2023-05-10 19:21
I made it, it is out as v0.11.1.4. Changes: https://github.com/lmagyar/homeassistant-addon-tailscale/commit/0c67af07a1a11b67884c1286da957ce80571cfa3

You have to add `userspace_networking: false` to the config to activate it.

Itt will add local subnets with higher priority to ip rules than Tailscale, and will remove it on add-on stop.

I tested it setting "Start on boot" and "Watchdog" to false (in case I brick the device, a power cycle can make it available again), then enabled subnet routing on another device with the same 192.168.1.0/24 network, and it survived it. I have restarted the add-on, and still survived it. So I think it works. :)

**Comment by lmagyar** [comment] 2023-05-11 10:44
FYI: And I made a PR toward the official add-on also. https://github.com/hassio-addons/addon-tailscale/pull/201

**Comment by lmagyar** [comment] 2023-05-21 07:58
Has anybody tested this subnet issue? (You have to add `userspace_networking: false` to the config to "activate" the issue and the workaround.)

**Comment by MayorBug** [comment] 2023-05-24 06:40
Been using your addon for tunnels since you made it available and had no issues with connection. But yea around two weeks ago I started also getting connection issues. Tought it was my router. Since rebooting the router makes the HA instance reachable again. 
Will try the flag and see how it goes

**Comment by MayorBug** [comment] 2023-05-24 07:18
With `userspace_networking: false`

![Screenshot_20230524-094918_Chrome](https://github.com/lmagyar/homeassistant-addon-tailscale/assets/11988477/a9bb292e-a390-4dcb-835d-2aa5718a5145)

**Comment by lmagyar** [comment] 2023-05-24 09:27
Thank you @MayorBug!
It seems route "manipulation" have some issue with IPv6, I will try to reproduce and fix it.

**Comment by lmagyar** [comment] 2023-05-25 11:42
New version v0.11.1.7 is out, with the bugfix for IPv6. (And with new Tailscale v1.42.0.)

```
[13:36:43] INFO: Adding route 192.168.1.0/24 to ip rules
[13:36:43] INFO: Adding route fd19:8efe:2a99::/64 to ip rules
```

**Comment by MayorBug** [comment] 2023-05-29 07:28
Been using with the `userspace_networking: false` flag now for 4days and it has been stable.

**Comment by lmagyar** [comment] 2023-06-23 09:33
Closing this now, as `userspace_networking: false` is quite stable, tested (v0.11.1.9) with site-to-site networking, even with real colliding subnets by misconfiguration (yeah, even when you know what you really don't want to do), and it survived everything.

**Closed by lmagyar** 2023-06-23 09:33 UTC
